export default {
	GET_CURRENT_LOCATION:"GET_CURRENT_LOCATION",
	GET_DRIVER_INFORMATION:"GET_DRIVER_INFORMATION",
	GET_DRIVER_LOCATION:"GET_DRIVER_LOCATION",
	GET_DISTANCE_FROM_DRIVER:"GET_DISTANCE_FROM_DRIVER"
};